name: Build Go Project and Create Release
on:
    push:
        branches: [release]

permissions:
    contents: write

jobs:
    build_and_release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.20.x"

            - name: Linux
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  go build -ldflags="-s -w" ./go/main.go -o glados-gpt

            - name: Upload Artifacts
              id: upload-artifacts
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ./go/glados-gpt
                      ./glados
                  
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: true
                  tag_name: v
                  name: tgpt
