name: Build Go Project and Create Release
on:
    push:
        branches: [release]

permissions:
    contents: write

jobs:
    build_and_release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-20.04]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.20.x"

            - name: Build
              if: matrix.os == 'ubuntu-20.04'
              run: |
                  go build -ldflags="-s -w" -o gpt-glados ./

            - name: Upload Artifacts
              id: upload-artifacts
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      ./gpt-glados
                      ./glados
                      ./GLaDOS-Installer.sh
                  
                  token: ${{ secrets.GITHUB_TOKEN }}
                  draft: true
                  tag_name: v
                  name: glados
                  body: |
                     # Changes
                     
                     
                     # How To Install
                     
                     1. Download **GLaDOS-Installer.sh**
                     2. Open The Terminal And Give It Execute Permitions (chmod +x ./GLaDOS-Installer.sh (make sure you're on the same folder as the file))
                     3. Execute It (./GLaDOS-Intsaller.sh)
                     4. Follow The Installer
                     5. Enjoy (To Execute Glados Run **glados**)
